default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: achieve_development
test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
